Repository VoltaML/voltaML-fast-stable-diffusion, pull requests merged in 2023-04, with the labels that each got.

#53 ToMeSD support
  core/config/config.py
  core/optimizations.py
  frontend/dist/assets/SettingsView.js
  frontend/dist/assets/index.js
  frontend/src/components/settings/APISettings.vue
  frontend/src/settings.ts
  requirements/pytorch.txt
Labels: Coming soon

#59 Add an option to install dependencies without running UI or checking for HF tokens
  main.py
  tests/test_main.py
Labels: Feature Request

#60 Self-Attention Guidance
  core/config/config.py
  core/inference/lwp_sd.py
  core/inference/pytorch.py
  core/inference/sag/cross_attn.py
  core/inference/sag/sag_utils.py
  core/types.py
  frontend/src/components/img2img/Img2Img.vue
  frontend/src/components/img2img/Inpainting.vue
  frontend/src/settings.ts
  frontend/src/views/TextToImageView.vue
Labels: Feature Request, Coming soon
