Repository VoltaML/voltaML-fast-stable-diffusion, pull requests merged in 2023-06, with the labels that each got.

#103 Added save_to_sub_folder setting and relevant code a toggle for the o…
  core/config/config.py
  core/png_metadata.py
  frontend/dist/assets/GenerateSection.vue_vue_type_script_setup_true_lang.js
  frontend/dist/assets/Image.js
  frontend/dist/assets/ImageUpload.js
  frontend/dist/assets/InputNumber.js
  frontend/dist/assets/SendOutputTo.vue_vue_type_script_setup_true_lang.js
  frontend/dist/assets/SettingsView.js
  frontend/dist/assets/Switch.js
  frontend/dist/assets/index.js
  frontend/src/components/settings/APISettings.vue
  frontend/src/settings.ts
Labels: Feature Request

#99 fix: use dotenv extra args
  .gitignore
  example.env
  main.py
  manager/src/environ.rs
  manager/src/main.rs
Labels: Bug

#104 Fix some spelling in the docs
  docs/developers/documentation.md
  docs/experimental/settings.md
  docs/getting-started/features.md
  docs/getting-started/introduction.md
  docs/index.md
  docs/installation/old.md
  docs/troubleshooting/linux.md
  docs/troubleshooting/windows.md
  docs/webui/download.md
  docs/webui/img2img.md
  docs/webui/txt2img.md
Labels: Bug, Documentation

#105 Make the Discord bot functional again
  bot/hardware.py
  bot/models.py
  bot/txt2img.py
  core/install_requirements.py
Labels: Bug, python
